# sam build && sam deploy --resolve-s3

version = 0.1

[default.deploy.parameters]
profile = "prx-it-services"
stack_name = "zendesk-toolkit"
s3_prefix = "zendesk-toolkit"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
region = "us-east-2"
# Parameter overrides only need to be included when a parameter is changing
# parameter_overrides = [
#   "PrxZendeskApiUsername=",
#   "PrxZendeskApiToken=",
#   "SlackAccessToken=",
#   "SlackSigningSecret=",
#   "SlackChannelId="
# ]
